ProjectR1/config/routes.rb
Rails.application.routes.draw do

  get 'users/index',to:'users#index'
  resources :photos do
  member do
    get 'display',controller:'photos',action:'display',to_param:[:photo_id]
  end
end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ProjectR1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ProjectR1/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

ProjectR1/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

ProjectR1/app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

ProjectR1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ProjectR1/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment_text, :date_time, :user_id, :photo_id)
    end
end

ProjectR1/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
   @userView = User.find(params[:id])
   @photos = @userView.photos

  end

  def display
    @user_id = params[:id]
    @user_photo = Photo.find(params[:id])
    @comments = @user_photo.comments
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:file_name, :date_time, :user_id)
    end
end

ProjectR1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to(photo_path)
  end

  # GET /users/1/edit
  def edit
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

ProjectR1/app/helpers/application_helper.rb
module ApplicationHelper
end

ProjectR1/app/helpers/comments_helper.rb
module CommentsHelper
end

ProjectR1/app/helpers/photos_helper.rb
module PhotosHelper
end

ProjectR1/app/helpers/users_helper.rb
module UsersHelper
end

ProjectR1/app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_text %>
    <%= f.text_field :comment_text %>
  </div>

  <div class="field">
    <%= f.label :date_time %>
    <%= f.date_select :date_time %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :photo_id %>
    <%= f.text_field :photo_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ProjectR1/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

ProjectR1/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment text</th>
      <th>Date time</th>
      <th>User</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment_text %></td>
        <td><%= comment.date_time %></td>
        <td><%= comment.user %></td>
        <td><%= comment.photo %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

ProjectR1/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

ProjectR1/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment text:</strong>
  <%= @comment.comment_text %>
</p>

<p>
  <strong>Date time:</strong>
  <%= @comment.date_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @comment.photo %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

ProjectR1/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#">PhotoShare</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= users_path %>">User List <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= users_path %>">Home</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

ProjectR1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectR1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

ProjectR1/app/views/photos/_form.html.erb
<%= form_for(photo) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %>
    <%= f.text_field :file_name %>
  </div>

  <div class="field">
    <%= f.label :date_time %>
    <%= f.date_select :date_time %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ProjectR1/app/views/photos/display.html.erb
<%= image_tag("/assets/#{@user_photo.file_name}", alt: "photos") %>
<p> Created on:<%= @user_photo.date_time %> </p>
<ul>
  <li id="Comment"><b> Comments: </b> </li>
  <% @comments.each do |comment| %>
      <li>
        <div class="panel panel-default">
          <div class="panel-heading"><b><%= comment.user.first_name %> <%=comment.user.last_name %>:</b></div>
           <div class="panel-body">
              <%= comment.comment_text %>
           </div>
        </div>
      </li>
  <% end %>
</ul>

<%= link_to 'Back', photo_path(@user_photo.user_id) %>

ProjectR1/app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

ProjectR1/app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Display page</h1>

ProjectR1/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

ProjectR1/app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<h1 id="photoShareHeader"> Photos of <%= @userView.first_name %></h1>

    <div class="row">
      <% @photos.each do |photo| %>
      <div class="col-xs-6 col-md-3">
        <a href="<%= display_photo_url(photo) %>" class="thumbnail">
          <%= image_tag("/assets/#{photo.file_name}", alt: "photos") %>
        </a>
      </div>
      <% end %>
    </div>


<%= link_to 'Back', users_path %>

ProjectR1/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ProjectR1/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

ProjectR1/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center" id="photoShareHeader">PhotoShare Users List</h1>

<div class ="Table">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">User List</div>

    <!-- Table -->
    <table class="table">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th colspan="3"></th>
      </tr>
      <tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= link_to 'Show Photos', user %></td>
          </tr>
      <% end %>
      </tr>
    </table>
  </div>


</div>

ProjectR1/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

ProjectR1/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Back', users_path %>